spring.application.name=parkingApp

spring.datasource.url=jdbc:mysql://localhost:3306/parking_app_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

# JWT Properties
#app.jwt-secret=MySuperSecretAndLongEnoughKeyForHS512Algorithm
#app.jwt-secret=ThisIsAMinimal64CharacterLongSecretKeyForHS512ThatWillJustWork1
# Presne 64-znakový k?ú? (512 bitov), aby sa predi?lo chybám pri kopírovaní.

app.jwt-secret=1234567890123456789012345678901234567890123456789012345678901234


app.jwt-expiration-milliseconds=604800000
  # 7 dní
